include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
     - lib/**.config.dart
     - lib/**.freezed.dart
     - lib/**.g.dart
     - lib/**.gr.dart
     - "**/*.g.dart"
     - "**/*.freezed.dart"

